---
- name: Expand root partition
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Get root path
    shell: |
      ostype=$(cat /etc/os-release | grep "^ID=" | cut -d "=" -f 2)
      rootpath="/dev/mapper/rl-root"
      if [[ $ostype == '"openEuler"' ]]; then
        rootpath="/dev/mapper/openeuler-root"
      fi
      echo $rootpath
    register: rootpath
  - name: Grow vda2
    shell: |
      result=$(growpart /dev/vda 2)
      if [[ $? == 0 ]]; then
        echo "$result"
      elif [[ $result == NOCHANGE* ]]; then
        echo "$result"
      else
        echo "$result"
        exit 1
      fi
  - name: Resize vda2
    shell: pvresize /dev/vda2
  - name: Extend root
    shell: |
      result=$(lvextend -l+100%FREE -n {{ rootpath.stdout }} 2>&1)
      if [[ $? == 0 ]]; then
        echo "$result"
      elif [[ $result == *'matches existing size'* ]]; then
        echo "$result"
      else
        echo "$result"
        exit 1
      fi
  - name: Resize root
    shell: resize2fs {{ rootpath.stdout }}
